# Generated by Django 2.2.2 on 2019-07-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='timestamp',
        ),
    ]
