# Generated by Django 2.2.3 on 2019-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_book_library1_section_teacher1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library1',
            name='books',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.RemoveField(
            model_name='section',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='students',
        ),
        migrations.DeleteModel(
            name='teacher1',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'computer science'), ('ise', 'information science'), ('mech', 'royalmech'), ('cl', 'civil engineering')], max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Student Name'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='library1',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
